#!/bin/bash
for ((counter=5; counter > 0; counter--)) do
    echo $counter
    sleep 1
done 
counter=$3
for ((counter; counter > 0; counter--)) do
    echo $counter
    # xdotool getmouselocation
    xdotool mousemove $1 $2 click 1 &
    echo "click" 
    if (( $(echo $4'<'1 | bc -l) )); then
        exit 1
    else 
        echo "sleep for $4 seconds" 
        sleep $4
        randNum=$(($RANDOM % 10))
        echo "sleep for $randNum seconds" 
        sleep $randNum
    fi
done
